name: Update apps & privacy data

on:
  schedule:
    - cron: "30 6 * * *"   # daily at 06:30 UTC (~07:30/06:30 IE depending on DST)
  workflow_dispatch: {}     # allow manual run

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Run updater
        env:
          USER_AGENT: "FiosFonBot/1.0 (contact: you@example.com)"
        run: npm run update:apps

      - name: Commit changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/apps.json data/privacy_cache || true
            git commit -m "chore(data): update apps & privacy labels [skip ci]"
            git push
          else
            echo "No changes."
          fi